### ISSUE TITLE
mandelbrot_imager.py not running

### ISSUE THREAD

**Issue by firehawk895** [MinhasKamal/CreepyCodeCollection#4]
```
Traceback (most recent call last):
  File "mandel.py", line 14, in <module>
    for X in j('BM'+P(M,v*x*3+26,26,12,v,x,1,24))or C:
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by MinhasKamal** [comment]
Are you working on python-3?

**Comment by firehawk895** [comment]
yes. could you explain the issue. python noob here.

**Comment by MinhasKamal** [comment]
There has been major changes of syntax in python-3 & it is not backward compatible, so codes written for previous versions will not work. I am not a pro either, see [here](http://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html) for details.
