### ISSUE TITLE
dilbert random number gen is wrong

### ISSUE THREAD

**Issue by hc5duke** [MinhasKamal/CreepyCodeCollection#5]
in: https://github.com/MinhasKamal/CreepyCodeCollection/blob/master/funny_and_hilarious.md

in the original comic, it returns 9 not 4: http://dilbert.com/strip/2001-10-25

**Comment by MinhasKamal** [comment]
Sorry! I changed the image to combine the two jokes. :(

**Comment by hc5duke** [comment]
ahh ok. gotcha 👍
